language: java
sudo: false
jdk: openjdk8
cache:
  directories:
    - $HOME/.m2
dist: xenial
script: | 
    mvn test
after_success:
  - mvn cobertura:cobertura
  - bash <(curl -s https://codecov.io/bash)